import test from 'node:test';
import assert from 'node:assert/strict';
import { ControlledExecutor, V2, type Request } from './execution-v2';
import { nativeAction } from './actions';
const target = { scope: 'DOCUMENT' as const, session: 's', activation: 'a', project_uuid: 'p', document_uuid: 'd', document_type: 'schematic', tab_id: 't' };
const request = (): Request => ({ protocol: V2, action: 'schematic.power.connect_pin', action_revision: '1', schema: 'test', request_id: 'r', operation_id: 'o', target_ref: target, input: { pinX: 0, pinY: 0, kind: 'power', net: 'VCC' }, budget_ms: 1000 });
function host(wait?: Promise<void>) { let flags: any[] = [], wires: any[] = []; let wireCalls = 0, flagCalls = 0; const create = async (_kind: string, net: string, x: number, y: number, rotation: number) => { flagCalls++; const id = net === '__ROTPROBE__' ? 'probe' : 'flag'; const f = { getState_PrimitiveId: () => id, getState_Net: () => net, getState_X: () => x, getState_Y: () => y, getState_Rotation: () => rotation }; flags.push(f); return f; }; (globalThis as any).eda = { sch_PrimitiveComponent: { getAll: async () => flags, createNetFlag: create, createNetPort: create, delete: async (ids: string[]) => { flags = flags.filter(x => !ids.includes(x.getState_PrimitiveId())); return true; } }, sch_PrimitiveWire: { getAll: async () => wires, create: async (points: number[]) => { wireCalls++; if (wait)
            await wait; const w = { getState_PrimitiveId: () => 'wire', getState_Line: () => points }; wires.push(w); return w; } } }; return { wireCalls: () => wireCalls, flagCalls: () => flagCalls }; }
test('connect_pin completes geometry and removes controlled calibration probe', async () => { const h = host(); const r = await new ControlledExecutor(nativeAction, async () => target).execute(request(), 'd'); assert.equal(r.verification.verdict, 'satisfied'); assert.equal(r.verification.residual, 0); assert.equal(h.wireCalls(), 1); assert.equal(h.flagCalls(), 2); });
test('connect_pin late wire settle never retries wire or starts flag after deadline', async () => { let settle!: () => void; const h = host(new Promise<void>(r => settle = r)), x = new ControlledExecutor(nativeAction, async () => target); const q = request(); q.budget_ms = 10; const pending = x.execute(q, 'd'); await new Promise(r => setTimeout(r, 30)); await assert.rejects(x.execute({ ...q, operation_id: 'second' }, 'e'), /BARRIER/); settle(); const result = await pending; assert.equal(result.effects.reconciled, true); assert.equal(result.verification.verdict, 'partial'); await x.reconcile('o'); await x.execute(q, 'd'); assert.equal(h.wireCalls(), 1); assert.equal(h.flagCalls(), 1); });
test('connect_pin target mismatch admits no calibration probe', async () => { const h = host(); const r = await new ControlledExecutor(nativeAction, async () => ({ ...target, document_uuid: 'foreign' })).execute(request(), 'd'); assert.equal(r.effects.effect_started, false); assert.equal(h.flagCalls(), 0); });
