package protocol

func closureActions() []ActionSpec {
	return []ActionSpec{
		{Name: "pcb.manufacturing.export", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Native Gerber archive including plated/nonplated drill plus BOM and PnP CSV. Explicit reviewed profile; File presence is unverified until CLI manifest inspects structure and revision. No CAM or ordering.", Inputs: []string{"project_uuid", "document_uuid", "profile:{id,reviewed:true,units:mm,layers:[IDs]}", "verification_ids optional"}, Outputs: []string{"manifest", "status", "artifacts", "warnings"}},
		{Name: "pcb.drc.compare", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Explicit whole-board native DRC and compact baseline comparison. No incremental DRC engine; missing stable anchors or incompatible context yields comparable:false. Full report retained as artifact.", Inputs: []string{"project_uuid", "document_uuid", "run_native:true", "baseline_id optional"}, Outputs: []string{"drc_id", "revision", "comparable", "new", "cleared", "persistent", "counts", "detailed_artifact"}},
		{Name: "pcb.plane.refresh", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Mutates: true, Description: "CLI composite: snapshot revision guard, native logical pour rebuild, authoritative snapshot. No incremental solver claim; connectivity unknown. Stops after uncertain outcome without replay.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "logical_ids"}, Outputs: []string{"status", "item_results", "revision_before", "revision_after", "requested_scope", "actual_scope", "freshness", "connectivity"}, VerifyWith: []string{"board.snapshot_compact"}},
		{Name: "pcb.routing_profile", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Read available Host context; record an immutable manufacturer-reviewed profile (evidence_basis:manufacturer, source_kind:manufacturer, evidence, reviewed, observed_layers_hash, rules_hash; stackup_hash computed from reviewed fields); validate against observable copper inventory/rules. Missing EDA 3.2 physical getter does not downgrade MANUFACTURER_VERIFIED; HOST_VERIFIED requires separate Host acceptance. No CAD mutation or impedance calculation. IDs are scoped to exact project/document.", Inputs: []string{"project_uuid", "document_uuid", "operation:context|put|get", "profile_id for get", "profile for put"}, Outputs: []string{"state", "stackup_hash", "rules_hash", "board_revision", "profile"}},
		{Name: "route.tuning_plan", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "EasyEDA equal-length settings on a caller-selected straight span/fixed corridor. Final target is current planar net copper length plus solved added length (no via barrel/package delay). GUI corners line_45/line_90/arc_90; W centerline spacing, H minimum excursion. Single corridor must select one side; bilateral alternates. follow_rule fails closed until one authoritative target can be resolved. Read-only plan; preflight/apply/readback/remeasure remain mandatory. No path/layer/corridor search.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "net", "span_id", "corridor [minX,minY,maxX,maxY] mil", "target_mode: specified_length|follow_rule", "target_length mil (specified_length)", "corner: line_45|line_90|arc_90", "side: single|bilateral", "spacing_w mil (centerline spacing)", "min_amplitude_h mil", "profile_id optional (verified single-ended)"}, Outputs: []string{"plan", "current_length", "target_length", "achieved_length", "added_length", "residual", "length_tolerance", "turns", "capacity_added_length", "corner", "side", "spacing_w", "min_amplitude_h", "actual_amplitude", "requires_preflight:true"}},
		{Name: "route.pair_plan", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Offset explicit P/N nets around caller centerline with straight miter corners, maximum 90-degree turns. Reject collapsing legs and gap violations; read-only, no obstacle search. Optional caller-specified endpoint transitions generate symmetric via/fanout geometry.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "positive_net", "negative_net", "layer", "width mil", "gap mil", "centerline [[x,y],...] mil", "transitions optional [{end:start|end,to_layer,diameter,hole,separation}]", "profile_id optional (verified differential width/gap)"}, Outputs: []string{"plan", "positive_length", "negative_length", "mismatch", "minimum_gap", "requires_preflight:true"}},
		{Name: "project.list", V2: &V2Action{Revision: "1", EffectScope: "NONE", Target: "ANY", Input: map[string]string{"team_uuid": "string", "folder_uuid": "string", "workspace_uuid": "string"}}, Domain: DomainProject, Phase: 1, NeedsWindow: true, Description: "Enumerate UUIDs in explicit native project scope; not a global name search. On EDA 3.2 an omitted scope can return [] even when Personal projects exist; this does not require team_uuid for Personal creation. Returns Connector activation token for create de-duplication.", Inputs: []string{"team_uuid optional", "folder_uuid optional", "workspace_uuid optional"}, Outputs: []string{"project_uuids", "scope", "scope_complete", "session_token"}},
		{Name: "project.create", Domain: DomainProject, Phase: 1, NeedsWindow: true, Mutates: true, Description: "Create one native project and read back exact UUID. Personal/Root: omit team_uuid and folder_uuid. project.current.teamUuid can be a personal owner UUID, not a real team UUID; never infer create scope from it. Pass team_uuid only for an explicitly selected real team. CLI/MCP accepts name-only Personal creation: Go acquires current identity/session and a transaction ID without copying owner/team. Explicit guard/session requests remain supported; select window when multiple sessions exist. Never retries a native create; uncertain requires reconciliation.", Inputs: []string{"name", "expected_project_uuid + session_token optional paired guards (Go acquires when omitted)", "client_transaction_id optional (Go generates when acquiring guards)", "team_uuid optional", "folder_uuid optional"}, Outputs: []string{"status:complete|uncertain", "project_uuid", "opened:false"}, VerifyWith: []string{"project.list"}},
		{Name: "project.open", Domain: DomainProject, Phase: 1, NeedsWindow: true, Description: "Open exact project UUID and verify current identity. Explicit window and expected current project UUID required. Save all edited pages before switching.", Inputs: []string{"project_uuid", "expected_project_uuid", "saved_current_project:true"}, Outputs: []string{"status:complete|uncertain", "opened", "project_uuid"}, VerifyWith: []string{"project.current"}},
		{Name: "schematic.create", Domain: DomainSchematic, Phase: 1, NeedsWindow: true, Mutates: true, Description: "Create a first schematic container in the explicitly guarded current project; read back container UUID and actual pages. Use existing schematic.page.create if no page exists, then schematic.page.open.", Inputs: []string{"expected_project_uuid", "session_token from project.list", "client_transaction_id", "board_name optional"}, Outputs: []string{"status:complete|uncertain", "schematic_uuid", "project_uuid", "pages", "opened:false"}, VerifyWith: []string{"schematic.pages.list"}},
	}
}
