package protocol

func closureActions() []ActionSpec {
	return []ActionSpec{
		{Name: "pcb.manufacturing.export", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Native Gerber archive including plated/nonplated drill plus BOM and PnP CSV. Explicit reviewed profile; File presence is unverified until CLI manifest inspects structure and revision. No CAM or ordering.", Inputs: []string{"project_uuid", "document_uuid", "profile:{id,reviewed:true,units:mm,layers:[IDs]}", "verification_ids optional"}, Outputs: []string{"manifest", "status", "artifacts", "warnings"}},
		{Name: "pcb.drc.compare", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Explicit whole-board native DRC and compact baseline comparison. No incremental DRC engine; missing stable anchors or incompatible context yields comparable:false. Full report retained as artifact.", Inputs: []string{"project_uuid", "document_uuid", "run_native:true", "baseline_id optional"}, Outputs: []string{"drc_id", "revision", "comparable", "new", "cleared", "persistent", "counts", "detailed_artifact"}},
		{Name: "pcb.plane.refresh", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Mutates: true, Description: "CLI composite: snapshot revision guard, native logical pour rebuild, authoritative snapshot. No incremental solver claim; connectivity unknown. Stops after uncertain outcome without replay.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "logical_ids"}, Outputs: []string{"status", "item_results", "revision_before", "revision_after", "requested_scope", "actual_scope", "freshness", "connectivity"}, VerifyWith: []string{"board.snapshot_compact"}},
		{Name: "pcb.routing_profile", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Read available Host context; record an immutable manufacturer-reviewed profile (evidence_basis:manufacturer, source_kind:manufacturer, evidence, reviewed, observed_layers_hash, rules_hash; stackup_hash computed from reviewed fields); validate against observable copper inventory/rules. Missing EDA 3.2 physical getter does not downgrade MANUFACTURER_VERIFIED; HOST_VERIFIED requires separate Host acceptance. No CAD mutation or impedance calculation. IDs are scoped to exact project/document.", Inputs: []string{"project_uuid", "document_uuid", "operation:context|put|get", "profile_id for get", "profile for put"}, Outputs: []string{"state", "stackup_hash", "rules_hash", "board_revision", "profile"}},
		{Name: "route.tuning_plan", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Generate an explicit rectangular tuning plan for one caller-selected axis-aligned trace span and fixed corridor. Read-only; requires subsequent preflight/apply. No path, layer, target or corridor search.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "net", "span_id", "corridor [minX,minY,maxX,maxY] mil", "target_added_length mil", "pitch mil", "min_spacing mil", "max_amplitude mil", "side +1 or -1 relative to span", "profile_id optional (verified single-ended)"}, Outputs: []string{"plan", "added_length", "residual", "turns", "capacity_added_length", "requires_preflight:true"}},
		{Name: "route.pair_plan", Domain: DomainPcb, Phase: 1, NeedsWindow: true, Description: "Offset explicit P/N nets around caller centerline with straight miter corners, maximum 90-degree turns. Reject collapsing legs and gap violations; read-only, no obstacle search. Optional caller-specified endpoint transitions generate symmetric via/fanout geometry.", Inputs: []string{"project_uuid", "document_uuid", "base_revision", "positive_net", "negative_net", "layer", "width mil", "gap mil", "centerline [[x,y],...] mil", "transitions optional [{end:start|end,to_layer,diameter,hole,separation}]", "profile_id optional (verified differential width/gap)"}, Outputs: []string{"plan", "positive_length", "negative_length", "mismatch", "minimum_gap", "requires_preflight:true"}},
		{Name: "project.list", Domain: DomainProject, Phase: 1, NeedsWindow: true, Description: "Enumerate UUIDs in explicit native project scope; not a global name search. Returns Connector activation token for create de-duplication.", Inputs: []string{"team_uuid optional", "folder_uuid optional", "workspace_uuid optional"}, Outputs: []string{"project_uuids", "scope", "scope_complete", "session_token"}},
		{Name: "project.create", Domain: DomainProject, Phase: 1, NeedsWindow: true, Mutates: true, Description: "Create one native project and read back exact UUID. Requires explicit window and expected current project UUID (empty only when none). Never retries a native create; uncertain requires reconciliation.", Inputs: []string{"name", "expected_project_uuid", "session_token from project.list", "client_transaction_id", "team_uuid optional", "folder_uuid optional"}, Outputs: []string{"status:complete|uncertain", "project_uuid", "opened:false"}, VerifyWith: []string{"project.list"}},
		{Name: "project.open", Domain: DomainProject, Phase: 1, NeedsWindow: true, Description: "Open exact project UUID and verify current identity. Explicit window and expected current project UUID required. Save all edited pages before switching.", Inputs: []string{"project_uuid", "expected_project_uuid", "saved_current_project:true"}, Outputs: []string{"status:complete|uncertain", "opened", "project_uuid"}, VerifyWith: []string{"project.current"}},
		{Name: "schematic.create", Domain: DomainSchematic, Phase: 1, NeedsWindow: true, Mutates: true, Description: "Create a first schematic container in the explicitly guarded current project; read back container UUID and actual pages. Use existing schematic.page.create if no page exists, then schematic.page.open.", Inputs: []string{"expected_project_uuid", "session_token from project.list", "client_transaction_id", "board_name optional"}, Outputs: []string{"status:complete|uncertain", "schematic_uuid", "project_uuid", "pages", "opened:false"}, VerifyWith: []string{"schematic.pages.list"}},
	}
}
